version: '3'

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./infrastructure:/work
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    working_dir: "/work/service"

  app:
    image: rust
    volumes:
      - ./infrastructure/functions:/work
    working_dir: "/work"
