version: 2.1

jobs:
  # build:
  #   docker:
  #     - image: circleci/rust
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build Lambda Functions
  #         command: make ci-build
  #     - save_cache:
  #         key: rust-{{ checksum "Cargo.lock" }}
  #         paths:
  #           - infrastructure/functions
  stage:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Stage AWS
          command: ./.circleci/stage.sh ${CIRCLE_BRANCH}
  destroy:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Destroy
          command: ./.circleci/destory.sh ${CIRCLE_BRANCH}


workflows:
  # build:
  #   jobs:
  #     - build
  stage:
    jobs:
      - stage
      - approval-destroy:
          type: approval
      - destroy
    # requires:
    #   - build
