version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Build Lambda Functions
          command: make ci-build
      - save_cache:
          key: rust-{{ checksum "Cargo.lock" }}
          paths:
            - infrastructure/functions
  stage:
    docker:
      - image: circleci/terraform
    steps:
      - checkout
      - run:
          name: Stage AWS
          command: make ci-stage

workflows:
  build_and_stage:
    jobs:
      - build
      - stage
