version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Build Lambda Functions
          command: ./.circleci/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - infrastructure/functions/lambda/target
      - save_cache:
          key: rust-{{ checksum "infrastructure/functions/lambda/Cargo.lock" }}
          paths:
            - infrastructure/functions/lambda
  stage:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Stage
          command: ./.circleci/stage.sh
  destroy:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Destroy
          command: ./.circleci/destroy.sh


workflows:
  staging:
    jobs:
      - build
      - stage:
          requires:
            - build
      - destroy
