version: 2.1

# commands:
#   check-merged:
#     parameters:
#       pattern:
#         type: string
#     steps:
#       - run:
#           command: git log --pretty=format:"%s" -n 1 $CIRCLE_SHA1

jobs:
  # build:
  #   docker:
  #     - image: circleci/rust
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build Lambda Functions
  #         command: make ci-build
  #     - save_cache:
  #         key: rust-{{ checksum "Cargo.lock" }}
  #         paths:
  #           - infrastructure/functions
  stage:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Stage AWS
          command: ./.circleci/stage.sh ${CIRCLE_BRANCH}
  destroy:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Check
          command: ./.circleci/merged.sh
      - run:
          name: Destroy
          command: ./.circleci/destroy.sh ${CIRCLE_BRANCH}


workflows:
  # build:
  #   jobs:
  #     - build
  stage:
    jobs:
      - stage
      # - approval-destroy:
      #     type: approval
      - destroy
          # requires:
          #   - approval-destroy
    # requires:
    #   - build
