version: 2.1

jobs:
  # build:
  #   docker:
  #     - image: circleci/rust
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build Lambda Functions
  #         command: make ci-build
  #     - save_cache:
  #         key: rust-{{ checksum "Cargo.lock" }}
  #         paths:
  #           - infrastructure/functions
  stage:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Stage
          working_directory: infrastructure/service
          command: ./.circleci/stage.sh
  destroy:
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Destroy
          working_directory: infrastructure/service
          command: ./.circleci/destroy.sh


workflows:
  # build:
  #   jobs:
  #     - build
  stage:
    jobs:
      - stage
      - destroy
    # requires:
    #   - build
